BASE_URL = "https://stellarburgers.education-services.ru"
REGISTER_URL = f"{BASE_URL}/api/auth/register"
LOGIN_URL = f"{BASE_URL}/api/auth/login"
ORDERS_URL = f"{BASE_URL}/api/orders"
USER_URL = f"{BASE_URL}/api/auth/user"